DOTENV=dotenv

start-forking-node-polygon-testnet:
	$(DOTENV) -e .env.polygon-amoy-testnet -- bunx hardhat node

start-forking-node-bsc-testnet:
	$(DOTENV) -e .env.bsc-testnet -- bunx hardhat node


start-forking-node-polygon-mainnet:
	$(DOTENV) -e .env.polygon-mainnet -- bunx hardhat node

start-forking-node-bsc-mainnet:
	$(DOTENV) -e .env.bsc-mainnet -- bunx hardhat node

start-forking-node-base-mainnet:
	$(DOTENV) -e .env.base-mainnet -- bunx hardhat node
