DOTENV=dotenv

start-forking-node-polygon-testnet:
	$(DOTENV) -e .env.polygon-amoy-testnet -- npx hardhat node

start-forking-node-bsc-testnet:
	$(DOTENV) -e .env.bsc-testnet -- npx hardhat node


start-forking-node-polygon-mainnet:
	$(DOTENV) -e .env.polygon-mainnet -- npx hardhat node

start-forking-node-bsc-mainnet:
	$(DOTENV) -e .env.bsc-mainnet -- npx hardhat node
